### ISSUE TITLE
$INFO[Window.Property(umbrella.moviesimilarlibrary)]

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.fuse.2#21]
### Skin section

Widgets

### Current Behavior

Previously the above would show what the Movie was similar to, on the home screen it just shows as Widget.

If I click into it though, it shows correctly

### Expected Behavior

To show what film similar to

### Steps To Reproduce

See images below

### Screenshots and Additional Info

![firetv_2024-10-07_15_21_58](https://github.com/user-attachments/assets/81140819-00f0-4157-9fc3-6ac6b91e07f5)
That's on widget page

![firetv_2024-10-07_15_22_11](https://github.com/user-attachments/assets/2688098b-b368-45ac-86ca-a9f86b5d81c6)
This is from within the addon

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I can't say how this property works as I don't make this addon. However, there is no reason why a `$INFO[]` label can't work as a widget title, so I don't think this is a skin issue.

**Comment by jurialmunkey** [comment]
The "Widget" label is the fallback label, so that means whatever you've entered as the widget label is empty.

**Comment by adamosborne83** [comment]
> The "Widget" label is the fallback label, so that means whatever you've entered as the widget label is empty.

I'll speak to UD, but this worked in AH2 and AF1.

**Comment by adamosborne83** [comment]
Really sorry J, but UD has changed nothing at all.

That code works fine in af1, anything different at all?

**Comment by jurialmunkey** [comment]
I haven't changed how the labels are handled or how widgets are edited. There's no reason for it to work in AF1 and not AF2. It sounds like an input error when typing it in or you're not using it in the same context etc.

**Comment by adamosborne83** [comment]
> I haven't changed how the labels are handled or how widgets are edited. There's no reason for it to work in AF1 and not AF2. It sounds like an input error when typing it in or you're not using it in the same context etc.

Sorry, I pestering Umbrella dev, and I think it's to do with Hubs, as on Umbrella set up, on Home it showed Similar too.... but when we create a hub it shows as widget.


![Screenshot_20241010_174804_Discord.jpg](https://github.com/user-attachments/assets/938a6987-6164-4c53-9300-b41171db87bb)

**Comment by jurialmunkey** [comment]
If the property is set to the home window then you must use `Window(home).property()` to access home window properties when inside other windows.

Window.Property() only accesses properties of the current window.

**Comment by adamosborne83** [comment]
> If the property is set to the home window then you must use `Window(home).property()` to access home window properties when inside other windows.
> 
> Window.Property() only accesses properties of the current window. 

Sorry, this is probably me being stupid,  but I only use Hub 1101, so it only shows as Widget in header.

But when umbrella dev tested for me, he just did it on default af2, which would have meant no hubs etc, but as soon as you do it in a hub, the $INFO[Window.Property(umbrella.moviesimilarlibrary)]

Does not work

**Comment by jurialmunkey** [comment]
>Sorry, this is probably me being stupid, but I only use Hub 1101, so it only shows as Widget in header.

Yes, and that's why what you're inputting doesn't work. There's no such property `Window(1101).Property(umbrella.moviesimilarlibrary)`

That's because the addon sets that property to the Home window, not 1101. If you want a property from another window other than the current window, then you must explicitly name it in the infolabel.

IF you want to retrieve the property from Home whilst not on the home screen, then you must use
`Window(Home).Property(umbrella.moviesimilarlibrary)`

**Comment by adamosborne83** [comment]
> >Sorry, this is probably me being stupid, but I only use Hub 1101, so it only shows as Widget in header.
> 
> Yes, and that's why what you're inputting doesn't work. There's no such property `Window(1101).Property(umbrella.moviesimilarlibrary)`
> 
> That's because the addon sets that property to the Home window, not 1101. If you want a property from another window other than the current window, then you must explicitly name it in the infolabel.
> 
> IF you want to retrieve the property from Home whilst not on the home screen, then you must use
> `Window(Home).Property(umbrella.moviesimilarlibrary)`

Thank you J, I must say I am really liking AF2, yes there are things I hugely miss from AF. 
Although, it's a trade off and speed is important to me. 

Honest thanks for everything and all the help over the years
